In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

pd.DataFrame(data_list)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
col = ['Name', 'Age','Location', 'Salary']
col

['Name', 'Age', 'Location', 'Salary']

In [8]:
n = pd.DataFrame(data_list, columns=col)
n

    Name  Age  Location  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
n['Location']

0    New York
1       Paris
2      Berlin
3      London
Name: Location, dtype: object

In [10]:
n[['Name','Location']]

    Name  Location
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [11]:
# to add a new coloumns
n['designation'] = ['Doctor','Engineer','Data Analyst','Doctor']

In [12]:
n

    Name  Age  Location  Salary   designation
0   John   28  New York   65000        Doctor
1   Anna   34     Paris   70000      Engineer
2  Peter   29    Berlin   62000  Data Analyst
3  Linda   42    London   85000        Doctor

In [14]:
n.drop('designation', axis = 1)
# by giving axis = 1 , it will look for designation in coloumns and perform the deletion operation

    Name  Age  Location  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
n

    Name  Age  Location  Salary   designation
0   John   28  New York   65000        Doctor
1   Anna   34     Paris   70000      Engineer
2  Peter   29    Berlin   62000  Data Analyst
3  Linda   42    London   85000        Doctor

In [17]:
# thus drop only will remove temporarily to remove permanently 
n.drop('designation',axis = 1, inplace = True)

In [18]:
n

    Name  Age  Location  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
n.drop(['Name','Location'], axis = 1)
# drop multiple colooumns

   Age  Salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [20]:
#  to remove rows, change the axis to zero
n.drop(0,axis = 0)

    Name  Age Location  Salary
1   Anna   34    Paris   70000
2  Peter   29   Berlin   62000
3  Linda   42   London   85000

In [21]:
# to retrieve rows => use loc
n.loc[0]

Name            John
Age               28
Location    New York
Salary         65000
Name: 0, dtype: object

In [23]:
n.loc[[0,1]]

   Name  Age  Location  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [24]:
# accessing data with index
n.iloc[3]

Name         Linda
Age             42
Location    London
Salary       85000
Name: 3, dtype: object

In [25]:
n

    Name  Age  Location  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
n.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [29]:
n[n['Age'] > 30]
# conditional stmt similar to numpy

    Name  Age Location  Salary
1   Anna   34    Paris   70000
3  Linda   42   London   85000

In [35]:
# to conditions together => above 30 and location must be paris
n[(n['Age'] > 30) & (n['Location'] == 'Paris')]

   Name  Age Location  Salary
1  Anna   34    Paris   70000